from pathlib import Path
import json, html, re

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'docs'/'fluxwalls'
BASE='https://thobg01.github.io/Wallpapers/fluxwalls/'

def esc(s): return html.escape(str(s),quote=True)

def main():
    catalog=json.loads((OUT/'catalog.json').read_text(encoding='utf-8'))
    groups={k:[e for e in catalog if e['orientation']==k] for k in ('mobile','desktop','square')}
    groups.update({k:[e for e in catalog if e['family']==k] for k in sorted({e['family'] for e in catalog})})
    catdir=OUT/'c'; catdir.mkdir(exist_ok=True)
    style='body{margin:0;background:#090b10;color:#f5f7fa;font:16px/1.5 system-ui}.w{width:min(1100px,calc(100% - 28px));margin:45px auto}a{color:inherit}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.card{text-decoration:none;background:#11151d;border:1px solid #252c37;border-radius:16px;padding:9px}.card img{width:100%;height:260px;object-fit:cover;border-radius:10px}.meta{color:#9aa5b5;font-size:.8rem}@media(max-width:800px){.grid{grid-template-columns:repeat(2,1fr)}.card img{height:230px}}'
    for name,items in groups.items():
        if not items: continue
        cards=''.join(f'<a class="card" href="../w/{e["slug"]}.html"><img loading="lazy" src="../assets/{e["asset"]}" alt="{esc(e["title"])}"><h3>{esc(e["title"])}</h3><div class="meta">{esc(e["orientation"])} · {e["width"]}×{e["height"]}</div></a>' for e in items[:96])
        title=f'Free {name.title()} Wallpapers — FluxWalls'
        desc=f'Browse free original {name} wallpapers generated by FluxWalls, with high-resolution SVG and PNG downloads.'
        page=f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)}</title><meta name="description" content="{esc(desc)}"><meta name="robots" content="index,follow"><link rel="canonical" href="{BASE}c/{name}.html"><style>{style}</style></head><body><main class="w"><p><a href="../">← FluxWalls</a></p><h1>{esc(name.title())} wallpapers</h1><p>{esc(desc)}</p><div class="grid">{cards}</div></main></body></html>'
        (catdir/f'{name}.html').write_text(page,encoding='utf-8')

    nav='<nav class="fw-discovery"><strong>Browse:</strong> '+ ' · '.join(f'<a href="c/{x}.html">{x.title()}</a>' for x in ('mobile','desktop','square')) + '</nav>'
    p=OUT/'index.html'; text=p.read_text(encoding='utf-8')
    if 'class="fw-discovery"' not in text:
        text=text.replace('<section class="grid">',nav+'<section class="grid">',1)
        p.write_text(text,encoding='utf-8')

    for e in catalog:
        p=OUT/'w'/f'{e["slug"]}.html'
        if not p.exists(): continue
        text=p.read_text(encoding='utf-8')
        # Refresh this block every run so older pages link to newly published wallpapers too.
        text=re.sub(r'<div class="fw-related">.*?</div>\s*', '', text, count=1, flags=re.S)
        related=[x for x in catalog if x['slug']!=e['slug'] and (x['orientation']==e['orientation'] or x['family']==e['family'])][:6]
        links=''.join(f'<a href="{x["slug"]}.html">{esc(x["title"])}</a> · ' for x in related)
        block=f'<div class="fw-related"><p><strong>Explore similar wallpapers:</strong> {links}<a href="../c/{e["orientation"]}.html">More {esc(e["orientation"])} wallpapers</a></p></div>'
        text=text.replace('</main>',block+'</main>',1)
        p.write_text(text,encoding='utf-8')

    urls=[BASE,BASE+'privacy.html']+[BASE+'c/'+k+'.html' for k,v in groups.items() if v]+[e['url'] for e in catalog[:1000]]
    sm='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'<url><loc>{u}</loc></url>\n' for u in urls)+'</urlset>\n'
    (OUT/'sitemap.xml').write_text(sm,encoding='utf-8')
    print('Enriched',len(catalog),'wallpapers and',sum(bool(v) for v in groups.values()),'category pages')

if __name__=='__main__': main()
